server:
  port: 8099

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/juansoto90/microservicebootcamp.git
          searchPaths: config-data
